runtime: nodejs18

service_account: app-engine-deployer@jenkins-cicd-demo-465510.iam.gserviceaccount.com

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

handlers:
- url: /.*
  script: auto
