name: Node_CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # You can change this to your required version

      - name: Install dependencies
        run: npm install
      - name: Install ci
        run: npm ci

   
       

      - name: Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      #- name: app create
        #run: gcloud app create --project=${{ secrets.GCP_PROJECT_ID }}  --region=asia-south1
     
      
      - name: Deploy to App Engine
        run: gcloud app deploy app.yaml --quiet --project=${{ secrets.GCP_PROJECT_ID }}

