name: Go_CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # Match app.yaml runtime: go122

      - name: Initialize Go module
        run: go mod init go-ci-cd

      - name: Tidy dependencies
        run: go mod tidy

      - name: Build application
        run: go
