  uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # Match app.yaml runtime: go122

      - name: Initialize Go module
        run: go mod init go-ci-cd

      - name: Tidy dependencies
        run: go mod tidy

      - name: Build application
        run: go
